### ISSUE TITLE
Not able to send emails from templates

### ISSUE THREAD

**Issue by hamzabinamin** [ecohealthalliance/parse-server-amazon-ses-email-adapter#7]
I get the following error whether its the html template or the txt one

```
web: (node:19332) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND email.https
web: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
```

@noamross @cmzambranat @ernestguevarra @collinschwantes @RobJY 

Guys can you please help?

**Comment by noamross** [comment]
Sorry, this project is no longer maintained.
